Proyecto1
=========
/*
		Investigación sobre el uso de Document.write
		DISCUSIÓN I 

*/

	document.write("<div class='n1'><h1> HEADING</h1></div>");
	document.write("<div class='n2'><p>I NEVER AM REALLY SATISFIED THAT I UNDERSTAND ANYTHING: BECAUSE, UNDERSTAND AND IT WELL AS I MAY. MY COMPRENHENSION CAN ONLY BE AND INFINITESIMAL FRACTION OF ALL I WANT TO UNDERSTAND ABOUT THE MANY CONNECTIONS AND RELATIONS WHICH OCCUR TO ME. HOW THE MATTER IN QUESTION WAS FIRST THOUGHT OF OR ARRIVED AT, ETC, ECT...</p></div>");
	document.write("<div class='n3'><p>IN ALMOST EVERY COMPUTATION A GREAT VARIETY OF ARRANGEMENTS FOR THE SUCCESSION OF THE PROCESSES IS POSIBLE, AND VARIOUS CONSIDERATIONS MUST INFLUENCE THE SELECTIONS AMONGST THEM FOR THE PURPOSES OF A CALCULATING ENGINE.</p></div>");
	document.write("<div class='n4'><p> Alexis Dueñas </p></div>");
